### PR TITLE
feat: Show Todo button only on User Login

### LINKED ISSUE #3: Show only todos button if user is logged in else show login and register button.
image

The authentication system is based on jwt. Users get the jwt token upon login which the user will use for subsequent access to todos without requiring to login again( for 5 days - cookie/jwt expiry time).

Now, It would be a great UX if the user doesn't see the login/register button on the homepage if he/she already has a valid cookie.

So, we can store an additional field in the response cookie along with jwt something like, isLoggedIn = true/false which we can use to render the buttons dynamically in EJS templates.

### PR DESCRIPTION
**Pull request by Zish303**
Fixes #3 

Changes:
I have modified the home page to show todo button only when there is valid jwt token.

Expected Outcome:
1. When the user is logged in, only Todo button is shown.
2. When the user is not logged in, only Login and Signup is button is shown.

### CODE REVIEW

**Comment by Zish303** [comment]
Please review and merge this PR.

**Comment by Yuvraj0157** [comment]
You are rendering buttons by initializing isLoggedIn in the home endpoint which only validates whether a cookie named jwt exists in the client request.
A possible flaw in the above approach is that the client may have an invalid cookie(may have created a fake JWT cookie using developer tools).
So, I suggest that you validate the cookie(if present) sent by the client as well and if it is valid then show todos bttn.
Otherwise, in case of no cookie, an invalid cookie show login/reg bttn.

**Comment by Zish303** [comment]
Done
I have a created a new middleware which validates the jwt token and return true/false if the token is valid.

**Comment by Yuvraj0157** [comment]
There is a small bug. you have to use "return next()" in the blocks or else other lines will be executed.

**Comment by Yuvraj0157** [comment]
I'll merge ur PR and change it.

**Pull request merged**
